# Generated by Django 5.2.6 on 2025-10-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_joining', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualfriend',
            name='choices',
        ),
        migrations.AddField(
            model_name='individualfriend',
            name='accommodation_preference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='individualfriend',
            name='accommodation_preference_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individualfriend',
            name='activity_preference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='individualfriend',
            name='activity_preference_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individualfriend',
            name='budget_preference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='individualfriend',
            name='budget_preference_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individualfriend',
            name='climate_preference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='individualfriend',
            name='climate_preference_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individualfriend',
            name='cuisine_preference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='individualfriend',
            name='cuisine_preference_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individualfriend',
            name='destination_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='individualfriend',
            name='destination_type_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
