# Generated by Django 5.2.6 on 2025-10-20 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends_joining', '0002_remove_individualfriend_choices_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualfriend',
            old_name='accommodation_preference_desc',
            new_name='destination_description',
        ),
        migrations.RemoveField(
            model_name='individualfriend',
            name='accommodation_preference',
        ),
        migrations.RemoveField(
            model_name='individualfriend',
            name='activity_preference',
        ),
        migrations.RemoveField(
            model_name='individualfriend',
            name='activity_preference_desc',
        ),
        migrations.RemoveField(
            model_name='individualfriend',
            name='budget_preference',
        ),
        migrations.RemoveField(
            model_name='individualfriend',
            name='budget_preference_desc',
        ),
        migrations.RemoveField(
            model_name='individualfriend',
            name='climate_preference',
        ),
        migrations.RemoveField(
            model_name='individualfriend',
            name='climate_preference_desc',
        ),
        migrations.RemoveField(
            model_name='individualfriend',
            name='cuisine_preference',
        ),
        migrations.RemoveField(
            model_name='individualfriend',
            name='cuisine_preference_desc',
        ),
        migrations.RemoveField(
            model_name='individualfriend',
            name='destination_type_desc',
        ),
    ]
