# Generated by Django 5.2.6 on 2025-10-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_joining', '0003_rename_accommodation_preference_desc_individualfriend_destination_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creating_group',
            options={},
        ),
        migrations.AlterModelOptions(
            name='preference_list',
            options={},
        ),
        migrations.RemoveField(
            model_name='individualfriend',
            name='destination_description',
        ),
        migrations.RemoveField(
            model_name='individualfriend',
            name='destination_type',
        ),
        migrations.AddField(
            model_name='individualfriend',
            name='destinations',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
